slangTerms = {
    'cook': {'definition': 'To do something impressively well', 'example': 'He really cooked with that project'},
    'cooked': {'definition': 'Exhausted or ruined', 'example': 'I’m cooked after that exam'},
    'sigma': {'definition': 'Independent or confident person', 'example': 'That’s such a sigma move'},
    'rizz': {'definition': 'Charm or charisma, often in flirting', 'example': 'He’s got crazy rizz'},
    'gyat': {'definition': 'Expression of surprise or admiration', 'example': 'Gyat! That’s wild'},
    'skibidi': {'definition': 'Playful nonsense or chaotic humor', 'example': 'That was so skibidi of him'},
    'ohio': {'definition': 'Weird or cursed vibe', 'example': 'This meme feels very Ohio'},
    'mewing': {'definition': 'Internet meme about jawline improvement', 'example': 'Can’t talk, I’m mewing'},
    'mogging': {'definition': 'Outshining or looking better than someone', 'example': 'He’s mogging everyone here'},
    'aura': {'definition': 'Overall vibe or energy someone gives', 'example': 'He’s got strong aura'},
    'glazing': {'definition': 'Overpraising or hyping someone excessively', 'example': 'Stop glazing him bro'},
    'bussin': {'definition': 'Extremely good or delicious', 'example': 'This food is bussin fr'},
    'no cap': {'definition': 'For real, no lie', 'example': 'That’s true, no cap'},
    'fr': {'definition': 'For real', 'example': 'That song hits hard fr'},
    'slay': {'definition': 'Do something flawlessly', 'example': 'She slayed that performance'},
    'ate': {'definition': 'Performed extremely well', 'example': 'She ate and left no crumbs'},
    'lowkey': {'definition': 'Somewhat secretly', 'example': 'I lowkey like that idea'},
    'highkey': {'definition': 'Definitely or obviously', 'example': 'That’s highkey awesome'},
    'mid': {'definition': 'Mediocre or average', 'example': 'That take was mid'},
    'based': {'definition': 'Unapologetically true to oneself', 'example': 'That’s a based opinion'},
    'ratio': {'definition': 'When a reply gets more likes than the original', 'example': 'Ratio + L + fell off'},
    'L': {'definition': 'Loss or failure (when used alone)', 'example': 'That’s an L'},
    'W': {'definition': 'Win or success (when used alone)', 'example': 'That’s a W'},
    'fire': {'definition': 'Awesome or excellent (not literal fire)', 'example': 'That song is fire'},
    'bet': {'definition': 'Agreement or confirmation', 'example': 'Bet, I’ll be there'}
}